name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build and Export
        run: npm run build && npm run export
        env:
          NEXT_PUBLIC_CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          NEXT_PUBLIC_CHATGPT_API_URL: ${{ secrets.CHATGPT_API_URL }}
          PORT: ${{ secrets.PORT }}
          NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL: ${{ secrets.EMAIL }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
