name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Build project
        run: npm run build:prod

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Decode SSH key
        run: echo "${{ secrets.NEW_DEPLOY_KEY }}" > id_rsa

      - name: Debug Secret Start
        run: echo "Start of DEPLOY_KEY is ${DEPLOY_KEY:0:15}"
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Debug Secret Length
        run: echo "Length of DEPLOY_KEY is ${#DEPLOY_KEY}"
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.NEW_DEPLOY_KEY }}

      - name: Add SSH host key
        run: ssh-keyscan -p 2233 -H ${{ secrets.SERVER_DOMAIN }} >> ~/.ssh/known_hosts

      - name: Deploy to cPanel
        run: |
          scp -P 2233 -r .next ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_DOMAIN }}:${{ secrets.DIRECTORY_NAME }}
          scp -P 2233 package.json ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_DOMAIN }}:${{ secrets.DIRECTORY_NAME }}
          scp -P 2233 server.js ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_DOMAIN }}:${{ secrets.DIRECTORY_NAME }}
          ssh -p 2233 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_DOMAIN }} "cd $${{ secrets.DIRECTORY_NAME }} && npm install --production && npm run server:prod"
